### PR TITLE
Add color transfer as in paper

### PR DESCRIPTION
**Pull request by cptq**
Adds code and a script for computing and plotting color transfer as in the paper. Instructions are in color-transfer/README.md.

### CODE REVIEW

**Comment by mblondel** [comment]
Thanks a lot Derek! 

Could you
* remove the .gitkeep files and add them to .gitignore
* add a license and our names at the top of each file as in [this file](https://github.com/mblondel/smooth-ot/blob/master/smoothot/projection.py#L1)
* move the color-transfer folder to the examples folder

I'll merge after that! Thanks a lot :)

**Comment by cptq** [comment]
Hi @mblondel thanks for taking a look. I think I made the changes you wanted.

**Comment by mblondel** [comment]
Two other comments before merging:

* If you use `root_dir = os.path.dirname(os.path.abspath(__file__))`, you will get the directory where the script (`dataset.py` or `plot_color_transfer.py`) is, regardless where it's executed from. You can then use, e.g., `os.path.join(root_dir, "..", "..", "data", "autumn.jpg")` to access particular files. I should have caught this before, sorry.
* the README file should be moved to the color-transfer folder

Thanks in advance.

**Comment by cptq** [comment]
I see, thanks for the tips, how does this look @mblondel ?

**Comment by mblondel** [comment]
Thanks a ton @cptq! Looking forward to see what comes out of your research!

**Pull request merged**
